const {
  assertNoClientActorUid,
  readActorAuthorization,
  readActorProfile,
  readAuthoritativeClaims,
  getTrustedActor,
  hasPermission,
  requirePermission,
  hasSystemRole,
  requireSystemRole,
  canManageCustomRole,
  requireCanManageCustomRole,
  canDelegateCustomRole,
  requireCanDelegateCustomRole,
  isRootActor,
  requireRootActor,
  SYSTEM_ROLES,
  PERMISSIONS,
} = require('./auth')

module.exports = {
  assertNoClientActorUid,
  readActorAuthorization,
  readActorProfile,
  readAuthoritativeClaims,
  getTrustedActor,
  hasPermission,
  requirePermission,
  hasSystemRole,
  requireSystemRole,
  canManageCustomRole,
  requireCanManageCustomRole,
  canDelegateCustomRole,
  requireCanDelegateCustomRole,
  isRootActor,
  requireRootActor,
  SYSTEM_ROLES,
  PERMISSIONS,
}
