const { authHealth } = require('./health')
const customRoleFunctions = require('./custom-role-functions')
const newsFunctions = require('./news-functions')
const systemRoleFunctions = require('./system-role-functions')
const userFunctions = require('./user-functions')
const authorizationRebuildFunctions = require('./authorization-rebuild-functions')
const membershipFunctions = require('./membership-functions')

exports.authHealth = authHealth
exports.createCustomRole = customRoleFunctions.createCustomRole
exports.listCustomRoles = customRoleFunctions.listCustomRoles
exports.updateCustomRole = customRoleFunctions.updateCustomRole
exports.disableCustomRole = customRoleFunctions.disableCustomRole
exports.enableCustomRole = customRoleFunctions.enableCustomRole
exports.deleteCustomRole = customRoleFunctions.deleteCustomRole
exports.assignCustomRole = customRoleFunctions.assignCustomRole
exports.revokeCustomRole = customRoleFunctions.revokeCustomRole
exports.setSystemRole = systemRoleFunctions.setSystemRole
exports.updateUserProfile = userFunctions.updateUserProfile
exports.listUsers = userFunctions.listUsers
exports.rebuildProtectedSystemRoleAuthorizations = authorizationRebuildFunctions.rebuildProtectedSystemRoleAuthorizations
exports.listMembershipTiers = membershipFunctions.listMembershipTiers
exports.listMemberships = membershipFunctions.listMemberships
exports.getUserMemberships = membershipFunctions.getUserMemberships
exports.createManualMembership = membershipFunctions.createManualMembership
exports.revokeMembership = membershipFunctions.revokeMembership
exports.createMembershipTier = membershipFunctions.createMembershipTier
exports.updateMembershipTier = membershipFunctions.updateMembershipTier
exports.deactivateMembershipTier = membershipFunctions.deactivateMembershipTier
exports.listNews = newsFunctions.listNews
exports.getNewsArticle = newsFunctions.getNewsArticle
exports.listNewsManagement = newsFunctions.listNewsManagement
exports.getNewsManagementArticle = newsFunctions.getNewsManagementArticle
exports.listNewsCategories = newsFunctions.listNewsCategories
exports.listNewsUsers = newsFunctions.listNewsUsers
exports.listNewsGroups = newsFunctions.listNewsGroups
exports.createNewsArticle = newsFunctions.createNewsArticle
exports.updateNewsArticle = newsFunctions.updateNewsArticle
exports.archiveNewsArticle = newsFunctions.archiveNewsArticle
exports.unarchiveNewsArticle = newsFunctions.unarchiveNewsArticle
exports.publishNewsArticle = newsFunctions.publishNewsArticle
exports.unpublishNewsArticle = newsFunctions.unpublishNewsArticle
exports.setNewsAccessPolicy = newsFunctions.setNewsAccessPolicy
exports.createNewsCategory = newsFunctions.createNewsCategory
exports.updateNewsCategory = newsFunctions.updateNewsCategory
exports.deleteNewsCategory = newsFunctions.deleteNewsCategory
exports.setNewsAclEntry = newsFunctions.setNewsAclEntry
exports.removeNewsAclEntry = newsFunctions.removeNewsAclEntry
