export const PERMISSIONS = Object.freeze({
  USERS_READ: 'users.read',
  USERS_CREATE: 'users.create',
  USERS_UPDATE: 'users.update',
  USERS_DELETE: 'users.delete',
  ROLES_READ: 'roles.read',
  ROLES_ASSIGN: 'roles.assign',
  ROLES_REVOKE: 'roles.revoke',
  CALENDAR_SEARCH: 'calendar.search',
  CALENDAR_EXPORT: 'calendar.export',
  CALENDAR_IMPORT: 'calendar.import',
  AUDIT_READ: 'audit.read',
  APPROVAL_CREATE: 'approval.create',
  APPROVAL_REVIEW: 'approval.review',
  NEWS_CREATE: 'news.create',
  NEWS_UPDATE: 'news.update',
  NEWS_DELETE: 'news.delete',
  NEWS_PUBLISH: 'news.publish',
})
